// src/views/ProfilePage.vue
<template>
  <div>
    <Hero :profileData="profileData.hero" />
    <About :profileData="profileData.about" />
    <Pricing v-if="profileData.pricing" :profileData="profileData.pricing" />
    <Skills v-if="profileData.skills" :profileData="profileData.skills" />
    <Portfolio :profileData="profileData.portfolio" />
    <Equipment v-if="profileData.equipment" :profileData="profileData.equipment" />
  </div>
</template>

<script>
import Hero from '../components/Hero.vue'
import About from '../components/About.vue'
import Skills from '../components/Skills.vue'
import Equipment from '../components/Equipment.vue'
import Portfolio from '../components/Portfolio.vue'
import Pricing from '../components/Pricing.vue'
import { profiles } from '../data/profiles.js'

export default {
  name: 'ProfilePage',
  components: { Hero, About, Skills, Equipment, Portfolio, Pricing },
  props: {
    profileKey: {
      type: String,
      required: true
    }
  },
  computed: {
    profileData() {
      return profiles[this.profileKey]
    }
  }
}
</script>

// src/views/ProfilePage.tsx
import Hero from '../components/Hero'
import About from '../components/About'
import Skills from '../components/Skills'
import Equipment from '../components/Equipment'
import Portfolio from '../components/Portfolio'
import Pricing from '../components/Pricing'
import { profiles } from '../data/profiles'

interface Props {
  profileKey: string
}

export default function ProfilePage({ profileKey }: Props) {
  const profileData = profiles[profileKey]

  return (
    <div>
      <Hero profileData={profileData.hero} />
      <About profileData={profileData.about} />
      {profileData.pricing && <Pricing profileData={profileData.pricing} />}
      {profileData.skills && <Skills profileData={profileData.skills} />}
      <Portfolio profileData={profileData.portfolio} />
      {profileData.equipment && <Equipment profileData={profileData.equipment} />}
    </div>
  )
}
