// src/App.tsx
import { BrowserRouter, Routes, Route, Navigate, useLocation } from 'react-router-dom'
import Header from './components/Header'
import Footer from './components/Footer'
import ProfilePage from './views/ProfilePage'
import styles from './App.module.css'

function AppLayout() {
  const location = useLocation()
  const currentProfile =
    location.pathname === '/my-profile/dev' ? 'webDeveloper' : 'soundEngineer'

  return (
    <div className={styles.app}>
      <Header currentProfile={currentProfile} />
      <main className={`container ${styles.main}`}>
        <Routes>
          <Route path="/" element={<ProfilePage profileKey="soundEngineer" />} />
          <Route path="/sound" element={<ProfilePage profileKey="soundEngineer" />} />
          <Route path="/dev" element={<Navigate to="/sound" replace />} />
        </Routes>
      </main>
      <Footer />
    </div>
  )
}

export default function App() {
  return (
    <BrowserRouter basename={import.meta.env.BASE_URL}>
      <AppLayout />
    </BrowserRouter>
  )
}

// src/App.vue
<template>
  <div class="app">
    <Header :currentProfile="currentProfile" />
    <main class="container">
      <router-view />
    </main>
    <Footer />
  </div>
</template>

<script>
import Header from './components/Header.vue'
import Footer from './components/Footer.vue'

export default {
  name: 'App',
  components: { Header, Footer },
  computed: {
    currentProfile() {
      return this.$route.meta?.profile || 'soundEngineer'
    }
  }
}
</script>

<style scoped>
.app {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
}

main {
  flex: 1;
  padding: 40px 20px;
}
</style>
